ROOT = ../..
include $(ROOT)/motif.mk

CCFLAGS = $(CC.OPTIMIZE) $(CC.DLL)

:ALL:

Mrm :MESSAGE_CATALOG:

Mrm 2.1 :LIBRARY: MrmIbuffer.c MrmIentry.c MrmIfile.c MrmIheader.c	\
	MrmIindex.c MrmIindexw.c MrmIrid.c MrmIswap.c MrmItop.c		\
	MrmItopw.c MrmMessages.c Mrmappl.c Mrmcontext.c Mrmerror.c	\
	Mrmhier.c Mrmicon.c Mrminit.c Mrmlread.c Mrmlwrite.c		\
	Mrmmodule.c Mrmos.c Mrmptrlist.c Mrmtable.c Mrmtime.c Mrmvm.c	\
	Mrmwci.c Mrmwcrw.c Mrmwcrwr.c Mrmwread.c Mrmwrefs.c		\
	Mrmwvalues.c Mrmwwrite.c
